camallo/dkregistry-rs

- tests/net/quay_io/mod.rs
This updates quay.io to use a different repository, as the previous
one has been removed.
> tests/net: update quay.io tests

- Cargo.toml
- README.md
- tests/mock/api_version.rs
- tests/mock/base_client.rs
- tests/mock/blobs_download.rs
- tests/mock/catalog.rs
- tests/mock/tags.rs
This update hyper-rustls and mockito to latest versions.
> cargo: bump hyper-rustls to 0.12

- src/v2/manifest/manifest_schema1.rs
- src/v2/manifest/manifest_schema2.rs
This documents the order used by this crate when listing
layers' digests.
> v2/manifest: document layers order

- Cargo.toml
- examples/checkregistry.rs
- examples/common/mod.rs
- examples/image.rs
- examples/login.rs
- examples/tags.rs
- examples/trace.rs
- src/lib.rs
- src/mediatypes.rs
- src/v2/auth.rs
- src/v2/blobs.rs
- src/v2/catalog.rs
- src/v2/manifest/mod.rs
- src/v2/mod.rs
- src/v2/tags.rs
- tests/mock/api_version.rs
- tests/mock/base_client.rs
- tests/mock/blobs_download.rs
- tests/mock/catalog.rs
- tests/mock/tags.rs
- tests/net/docker_io/mod.rs
- tests/net/gcr_io/mod.rs
- tests/net/quay_io/mod.rs
This change is motivated by an out-of-band discussion with @lucab and a comment on a related PR https://github.com/openshift/cincinnati/pull/4#discussion_r225639618 by @crawford, suggesting to use future chaining.
Before this PR all methods return a `Result<Future..>` chaining them requires to `unwrap()` or slightly milder `unwrap_or_else()` for *every* additional chain element, which adds significant boilerplate for the consumer. This PR aims to aid with this by removing the outer `Result<Future..>` and return `Future..` for all async public methods.
I'd like to discuss this API breaking change with the intention to move forward with this or a similar approach for the whole crate. I've done a rewrite of the login example demonstrates the usage of the changed API.
---
- Rewrite examples …
> API: substitute `Result<Future..>` with `Future..` for more idiomatic future chaining

- src/lib.rs
- src/v2/tags.rs
- tests/mock/tags.rs
- tests/net/quay_io/mod.rs
This adds full support for tags pagination, with per-page limit
and next page following.
> v2/tags: follow results on multiple pages

- examples/image-labels.rs
- src/v2/manifest/manifest_schema1.rs
- tests/fixtures/quayio_steveej_cincinnati-test-labels_dkregistry-test.json
- tests/manifest.rs
Partial fix (v2s1 only) for #57.
> manifest/v2s1: add `get_labels()` method, test and example

- examples/image-labels.rs
Minor cleanup of compiler warnings in examples.
> examples/image-labels: remove unused imports

- Cargo.toml
- src/lib.rs
- src/v2/blobs.rs
This change is motivated by improved status error handling.
Before this change even error codes would be treated as success and the
body would contain the HTML formatted error message passed through to
the caller.
Instead of reimplementing proper error handling here we can make use of
the reqwest library which already does it.
---
Closes #63 
Progress on #44
> blobs: switch from hyper to reqwest

- src/v2/blobs.rs
- src/v2/mod.rs
> Reuse the token set by hyper for reqwest calls

- tests/mod.rs
- tests/net/quay_io/mod.rs
Add a login test for quay.io. Credentials for a dedicated CI user
are set up on travis.
> tests/quay: test authenticated methods

- Cargo.toml
- examples/checkregistry.rs
- examples/image-labels.rs
- examples/image.rs
- examples/login.rs
- examples/tags.rs
- examples/trace.rs
- src/lib.rs
- src/v2/config.rs
- src/v2/mod.rs
- tests/mock/api_version.rs
- tests/mock/base_client.rs
- tests/mock/blobs_download.rs
- tests/mock/catalog.rs
- tests/mock/tags.rs
- tests/net/docker_io/mod.rs
- tests/net/gcr_io/mod.rs
- tests/net/quay_io/mod.rs
@lucab PTAL and let me know if I'm missing something or if the handle is indeed unused
> dkregistry: remove tokio-core, use tokio instead

- src/mediatypes.rs
Since recently quay.io appends `; charset=utf-8` in the `content-type`
header value for HEAD requests on the `manifests` endpoint. This patch
restores functionality as before the quay.io change.
> mediatypes: add band-aid for quay.io handling

- src/v2/auth.rs
- src/v2/manifest/mod.rs
- src/v2/mod.rs
This method returns the manifestref in addition to the manifest.  As
part of the migration to reqwest the method is a rewrite of
`get_manifest(..)`, which now wraps the new one and omits the
manifestref from the result.
>  v2/manifest: add get_manifest_and_ref method

- Cargo.toml
Reverts camallo/dkregistry-rs#84.
Fixes #87.
> Revert "Update hyper-rustls requirement from 0.15 to 0.16"

- examples/common/mod.rs
- examples/image-labels.rs
- examples/image.rs
- examples/login.rs
- examples/tags.rs
- examples/trace.rs
* Only login when actually necessary, as not all registries seem to support authentication in the way we do it here.
* Improve the argument handling for some examples
> examples: improve authentication and argument handling

- Cargo.toml
- src/errors.rs
- src/lib.rs
- src/reference.rs
- tests/reference.rs
This reworks the reference parser in order to better handle references with custom hostnames.
Supersedes: https://github.com/camallo/dkregistry-rs/pull/93
> reference: rework custom hostname handling

- Cargo.toml
- README.md
This exposes two underlying TLS feature flags from reqwest, allowing
consumers to pick openssl (default) or rustls implementation.
Closes https://github.com/camallo/dkregistry-rs/pull/86 (superseded).
> cargo: expose reqwest TLS feature flags

- Cargo.toml
This bumps the minor version component, as there are been several API
changes since previous release.
> cargo: bump minor field after API changes

- Cargo.toml
- examples/trace.rs
- src/lib.rs
- src/v2/blobs.rs
- src/v2/content_digest.rs
- src/v2/mod.rs
- tests/mock/blobs_download.rs
Motivation for this is to detect if a registry sends a blob which doesn't match its layer digest.
TODO
---
Depends on #104.
> v2: add content digest module and verify blob integrity on download

- examples/checkregistry.rs
- examples/image.rs
- examples/login.rs
- examples/tags.rs
- examples/trace.rs
- src/lib.rs
- src/mediatypes.rs
- src/reference.rs
- src/v2/auth.rs
- src/v2/blobs.rs
- src/v2/catalog.rs
- src/v2/manifest/mod.rs
- src/v2/mod.rs
- src/v2/tags.rs
This is required for consumers who want to use these methods in a
multi-threaded program.
Along the way some error conversion had to be changed.
> v2: add `Send` bound to most of the API

- Cargo.toml
This updates cargo-release metadata, making sure we are using our
specific settings instead of the defaults.
> cargo: update release metadata

- Cargo.toml
- examples/checkregistry.rs
- examples/common/mod.rs
- examples/image-labels.rs
- examples/image.rs
- examples/login.rs
- examples/tags.rs
- examples/trace.rs
- src/lib.rs
- src/mediatypes.rs
- src/reference.rs
- src/render.rs
- src/v2/auth.rs
- src/v2/blobs.rs
- src/v2/catalog.rs
- src/v2/config.rs
- src/v2/content_digest.rs
- src/v2/manifest/manifest_schema1.rs
- src/v2/manifest/manifest_schema2.rs
- src/v2/manifest/mod.rs
- src/v2/mod.rs
- src/v2/tags.rs
- tests/manifest.rs
- tests/mock/blobs_download.rs
- tests/net/quay_io/mod.rs
- tests/reference.rs
> Switch to Rust edition 2018

- tests/net/quay_io/mod.rs
This is a temporary measure to unblock CI.
See #135.
> tests/net/quay: ignore insecure test

- src/v2/manifest/mod.rs
- tests/net/quay_io/mod.rs
This is a lightweight alternative for get_manifest_and_ref, which
doesn't fetch the whole manifest. It can be used to ensure tag didn't
change content-digest.
This is a precondition to cache manifests in Cincinnati if the tag didn't change content digest.
Ref: https://issues.redhat.com/browse/OTA-167
> v2/manifest: add a function to fetch content-digest for a tag

- src/v2/auth.rs
- src/v2/blobs.rs
- src/v2/catalog.rs
- src/v2/config.rs
- src/v2/manifest/manifest_schema2.rs
- src/v2/manifest/mod.rs
- src/v2/mod.rs
- src/v2/tags.rs
This commit ensures reqwest client is created once and reused across calls
> Reuse reqwest::Client

- src/v2/config.rs
This allows to ignore invalid TLS certificates which can be useful in
test environments.
> v2/client: add accept_invalid_certs option

- src/v2/auth.rs
- tests/net/docker_io/mod.rs
Before the refactor of the auth logic (5a4ec71136d3c70d3675f11719a0788cb28eea7f) we could pull from `docker.io` without credentials.
After the commit that behaviour has changed and we unfortunately need to provide valid credentials as otherwise we can't pull from Docker Hub.
This PR adds back support for pulling from Docker Hub
> Allow authentication without credentials for docker.io repo

- Cargo.toml
- examples/image-labels.rs
- src/errors.rs
- src/lib.rs
- src/mediatypes.rs
- src/reference.rs
- src/render.rs
- src/v2/auth.rs
- src/v2/blobs.rs
- src/v2/catalog.rs
- src/v2/content_digest.rs
- src/v2/manifest/manifest_schema1.rs
- src/v2/manifest/manifest_schema2.rs
- src/v2/manifest/mod.rs
- src/v2/mod.rs
- src/v2/tags.rs
- tests/mock/base_client.rs
- tests/mod.rs
- tests/net/quay_io/mod.rs
- `error-chain` generates Error type which is not `Sync`, so it is hard to use with many other libraries.
- Libraries are encouraged to provide structured error details instead of just formatted message.
- `errors::Error` type is now plain enum, using `thiserror` for `Display` and `From` impls.
- It is very large, but I don't think it is significant drawback.
- Some functions return custom Error type (which is more convenient to use), but such types can be converted to `errors::Error`.
- Unfortunately new approach does not play well with backtraces. I think this can be fixed if needed.
- In several places I replaced `?` with `expect` because there should not be any errors in fact.
> Use thiserror for error handling

- src/v2/manifest/mod.rs
If getting a 404 response when calling `has_manifest` then if the content-type returned for the json error body is `application/json; charset=utf-8` then the call to `evaluate_media_type` will fail with a strum error because it does not expect the `charset=utf-8` param to be valid here. see discussion in: https://github.com/camallo/dkregistry-rs/pull/113
This change follows the approach taken in other methods above which is to match on `status` before continuing to inspect the media type.
> fix has_manifest for 404 responses - do not evaluate_media_type()

- Cargo.toml
- src/v2/auth.rs
was generating invalid query strings with multiple scopes, eg:
```
.authenticate(&["repository:foo:pull", "repository:bar:pull"])
```
is serialised as:
```
?service=...&scope=repository:foo:pullscope=repository:bar:pull
```
note the missing '&' between pull and scope.
> fix: correctly separate multiple scopes with '&'

- src/errors.rs
This displays the error details in the error's string format.
> errors: include reqwest error details

- src/v2/mod.rs
This method can be used to evaluate if a client instance is authorized
to at least call the `v2` endpoint on the remote registry.
> client: add method to evaluate authorization status

- Cargo.toml
This won't be implied with `sign-commit` in the next minor release of
`cargo release`, so setting it explicitly to retain the current
behavior.
Closes #183
> Cargo: enable tag signing

- .travis.yml
- Cargo.toml
I didn't manage to change this dependency from the consumer of dkregistry so I'm resorting to downgrading it here.
Includes #190.
> Cargo: downgrade async-stream for compatibility with rust 1.43

- .travis.yml
This is to ensure that dkregisty-rs doesn't break compatibility with
the [rhel8/rust-toolset container][0].
[0]: https://catalog.redhat.com/software/containers/rhel8/rust-toolset/5b9c6aa85a134643ef2ecc63
> travis: run with rust 1.43.1

- .travis.yml
- Cargo.toml
All blockers seem to be gone, so tokio can be updated!
ref: https://github.com/camallo/dkregistry-rs/pull/188
@steveeJ
> Update to tokio 1.0 and reqwest 0.11

- src/v2/manifest/mod.rs
I've updated the `has_manifest` function to send a HEAD request, as the response body isn't used.
> Send HEAD, not GET, when checking manifest existence

- .github/workflows/minimal.yml
- .travis.yml
- src/errors.rs
- src/lib.rs
- src/mediatypes.rs
- src/reference.rs
- src/render.rs
- src/v2/blobs.rs
- src/v2/catalog.rs
- src/v2/config.rs
- src/v2/content_digest.rs
- src/v2/manifest/mod.rs
- src/v2/tags.rs
Travis CI is often failing, insecure and may be not be easy to retrigger. Github Actions are more flexible and integrate with Github nicely
> Replace travis CI with Github Actions

- .github/workflows/minimal.yml
test-net-private tests may be unstable, so we should not block on these
> github actions: move test-net-private tests to a separate suite

- tests/mock/api_version.rs
- tests/mock/base_client.rs
- tests/mock/blobs_download.rs
- tests/mock/catalog.rs
- tests/mock/tags.rs
- tests/net/docker_io/mod.rs
- tests/net/gcr_io/mod.rs
- tests/net/quay_io/mod.rs
- tests/reference.rs
Since tokio 1.0 `runtime` in test can be immutable
> tests: tokio runtime no longer needs to be mutable

- src/v2/auth.rs
Closes #210 
I made the following changes to make the header parsing case-insensitive:
- adapted the Regex to match method and key case-insensitively. This also required some changes in the positioning of whitespace character classes (\s) to not break the group matching.
- convert the matched method to lowercase
- rename lowercase method to PascalCase when deserializing using serde annotation
- convert all matched keys to lowercase
I also extended the relevant tests to include some variations in upper/lowercase methods and keys.
> make Www-Authentication header parsing case-insensitive

- src/mediatypes.rs
- src/v2/config.rs
- src/v2/manifest/mod.rs
- src/v2/mod.rs
Some registries don't parse weight parameter correctly, some require custom parameter weights.
This commits allows passing custom set of accepted types (with optional weight) and moves GCR workaround from v2/manifest/mod.rs to config.rs.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2010497
> Allow passing custom set of accepted types with optional weight

- .github/workflows/minimal.yml
`actions-rs/cargo@v1` ignores `env`, so we got 419 errors there as creds were not actually passed.
https://github.com/vrutkovs/dkregistry-rs/runs/4458280474
> github: run test-net-private via shell

- .github/workflows/minimal.yml
Run tests on Rust 1.58.0 at minimum
> Bump MSRV to 1.58.0

- Cargo.toml
- src/errors.rs
- src/v2/blobs.rs
- src/v2/content_digest.rs
- tests/mock/blobs_download.rs
Here we need this functionality: https://github.com/tailhook/vagga/pull/572
> Fetch blob as stream

- src/lib.rs
- src/mediatypes.rs
- src/v2/config.rs
- src/v2/manifest/manifest_schema2.rs
- src/v2/manifest/mod.rs
- src/v2/tags.rs
ManifestList images also known as fat-manifests are
collections of manifests for different arch/os.
this pr adds support for ManifestList images.
As manifest list images only contain digests of the
images contained in the manifest, the `layers_digests`
function returns the digest of all the images
contained in the ManifestList instead of individual
layers of the manifests.
The layers of a specific image from manifest list can
be obtained using the digest of the image from the
manifest list and getting it's manifest and manifestref
(get_manifest_and_ref()) and using this manifest of
the individual image to get the layers.
> add support for ManifestList images

- src/v2/tags.rs
- tests/mock/mod.rs
- tests/mock/tags_dockerv2.rs
- tests/mock/tags_quay.rs
This library does not work for listing tags with some registries such as JFrog's Artifactory, as the Artifactory Docker Registry does not use the "next_page" url query parameter. 
This Pull Request solves that issue by extracting all the query parameters returned in the Link Header provided by the registry server and uses them to fetch the next page of tags. 
This ensures a better alignment with the spec for tag pagination as defined by the docker API v2 Spec [Here](https://docs.docker.com/registry/spec/api/#pagination-1), while also maintaining compatibility with servers that use the "next_page" url query parameter such as quay.
> Modified Tag Pagination to get all query parameters from Link Header.

- src/render.rs
This lets users supply a callback receiving the path of each file in the image to selectively filter which files are unpacked into the destination directory.
> render: Add filter_unpack

- .github/workflows/minimal.yml
- Cargo.toml
- src/v2/auth.rs
The `colored` crate, a dependency of `mockito`, requires rust 1.70 or newer.
Also resolve a `clippy` warning.
Does not resolve the `HTTP 429 Too Many Requests` errors coming from the integration tests using `quay.io`
> Increase MSRV to 1.70 due to colored crate dependency

- .github/workflows/minimal.yml
- Cargo.toml
- examples/checkregistry.rs
- examples/image-labels.rs
- examples/image.rs
- examples/login.rs
- examples/tags.rs
- examples/trace.rs
- src/reference.rs
- src/v2/auth.rs
- src/v2/blobs.rs
- src/v2/catalog.rs
- src/v2/content_digest.rs
- src/v2/manifest/mod.rs
- src/v2/mod.rs
- src/v2/tags.rs
- tests/reference.rs
https://github.com/actions-rs/meta is in the read-only mode. Google tells me https://github.com/actions-rust-lang/setup-rust-toolchain is popular.
I tested the workflow (with a new Rust version which will come with a separate pull https://github.com/camallo/dkregistry-rs/pull/268) with my own fork of this repo and it works [there](https://github.com/hongkailiu/dkregistry-rs/pull/2).
It removed the `profile` and `override` fields in the toolchain step.
The `profile` field is no longer supported and the `override` field
is default to `true` [1].
---
Update:
To fix the following error from https://github.com/camallo/dkregistry-rs/actions/runs/15149290276/job/42635397177?pr=267, we bump the Rust version in this PR:
```
Downloaded adler32 v1.2.0
error: package `icu_normalizer_data v2.0.0` …
```
> Fix github actions

- Cargo.toml
dkregistry-rs blocks cincinnati from bumping reqwest version:
```console
$ cincinnati git:(o-master) git --no-pager log --pretty=oneline -1
05fabafcd5ba15ed1a483716e5ae925d628433f7 (HEAD -> o-master, origin/master, origin/HEAD) Merge pull request #1007 from hongkailiu/ubi9-everywhere
$ cargo tree | grep dkr -A20
├── dkregistry v0.5.1-alpha.0 (https://github.com/camallo/dkregistry-rs.git?rev=0a3c99b7ede0c177a4389e0ffd9e566572633f8c#0a3c99b7)
│   ├── async-stream v0.3.6
│   │   ├── async-stream-impl v0.3.6 (proc-macro)
│   │   │   ├── proc-macro2 v1.0.89 (*)
│   │   │   ├── quote v1.0.37 (*)
│   │   │   └── syn v2.0.85 (*)
│   │   ├── futures-core v0.3.30
│   │   └── pin-project-lite v0.2.12
│   ├── base64 v0.13.1
│   ├── bytes v1.5.0
│   ├── futures v0.3.30 (*)
│   ├── libflate v1.2.0
│ …
```
> Bump reqwest from 0.11 to 0.12
